export const elements = {
    appShell: document.getElementById('appShell'),
    categoryLayout: document.getElementById('categoryLayout'),
    categoryNav: document.getElementById('categoryNav'),
    categorySummary: document.getElementById('categorySummary'),
    inputPanel: document.getElementById('inputPanel'),
    calculatorToggleButton: document.getElementById('calculatorToggleButton'),
    calculatorToggleLabel: document.getElementById('calculatorToggleLabel'),
    panelTitle: document.getElementById('panelTitle'),
    inputValue: document.getElementById('inputValue'),
    inputUnit: document.getElementById('inputUnit'),
    genericInputControls: document.getElementById('genericInputControls'),
    categoryMeta: document.getElementById('categoryMeta'),
    categoryCustomContent: document.getElementById('categoryCustomContent'),
    resultsPanel: document.getElementById('resultsPanel'),
    resultsTitle: document.getElementById('resultsTitle'),
    resultsCount: document.getElementById('resultsCount'),
    resultsGrid: document.getElementById('resultsGrid'),
    currencySettingsModal: document.getElementById('currencySettingsModal'),
    currencySettingsTitle: document.getElementById('currencySettingsTitle'),
    currencySettingsBody: document.getElementById('currencySettingsBody'),
    closeCurrencySettings: document.getElementById('closeCurrencySettings'),
    themeToggle: document.getElementById('themeToggle'),
    themeToggleIcon: document.getElementById('themeToggleIcon'),
    themeToggleLabel: document.getElementById('themeToggleLabel'),
    toast: document.getElementById('toast'),
    toastLabel: document.getElementById('toastLabel')
};